### ISSUE TITLE
small bug : when i launch the app 7 times out of 10 I to need to set Prod.keys folder

### ISSUE THREAD

**Issue by larg000** [trembon/switch-library-manager#36]
when i launch the app 
it downloads updated titles and seem to scan folders 

then 7 times out of 10 I to need to set Prod.keys folder again

![Sans titre](https://github.com/trembon/switch-library-manager/assets/125519402/45bf9af0-c10f-47dd-83a9-316ca88ec1c2)

**Comment by larg000** [comment]
could there be a problem when reading settings.json ?
same problem that could delete url variable for some reason ?

**Comment by harvestry-of-ghosts** [comment]
@larg000 As stated in the other issue, the url variables don't ever disappear on my end. Have you tried running as an administrator and/or setting the settings.json to read only after you've configured it the way you want?

**Comment by larg000** [comment]
it's not an administrator right problem.
some times the app starts ok sometime not.
maybe a problem of access right  and priority on reading file settings.json at the same time in the app
that could also explain the other bug

**Comment by mspykerez** [comment]
This problem is not exclusive of this fork, it also used to happen from time to time with giwty original build.
If you close the app and relaunch it should fix without the need to have to rescan everything.

**Comment by larg000** [comment]
I know this problem is not exclusive to this fork.
However, closing the application and restarting it, does not solve the problem.

**Comment by larg000** [comment]
*edit, update info about the bug

start process seems not reach 100%
it always occurs after it downloaded updated titles db and start processing title update approximatively at 75%.

**Comment by harvestry-of-ghosts** [comment]
I have started experiencing this as well. There seems to be no rhyme or reason for when it happens. Sometimes it opens fine, sometimes it wants me to set game folder and prod.keys location when it gets to 75%. Seems completely random.

**Comment by trembon** [comment]
the prod.keys should hopefully be fixed with #45, havent had time to test it fully yet though

**Comment by harvestry-of-ghosts** [comment]
> the prod.keys should hopefully be fixed with #45, havent had time to test it fully yet though

Still happening.

**Comment by harvestry-of-ghosts** [comment]
Still happening on 1.7.0.

![Clipboard_08-18-2024_01](https://github.com/user-attachments/assets/1f9204e4-bee4-4661-be71-53a5f652b6e8)

**Comment by trembon** [comment]
i rewrote how the app loads the prod.keys now and removed the support for changing the prod.keys to not confuse people by having the settings overwritten
also added some logging to see where the prod.keys file is loaded from

**Comment by harvestry-of-ghosts** [comment]
Thanks for the update. It's crashing and closing for now due to tinfoil.media/repo/db/titles.json being down with the message "404 - File or directory not found. The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable."

Hopefully it's not permanent. Will try again later today.

**Comment by trembon** [comment]
update to try fix some of these problems are released with 1.8.0

**Comment by harvestry-of-ghosts** [comment]
Same thing still happening.

@larg000 Are you able to test and confirm/deny if it's also still occurring for you?

**Comment by larg000** [comment]
i confirm this is still occurring for me at same ratio

**Comment by trembon** [comment]
wierd, i am unable to reproduce this on my computer, so it is hard to try and fix it :/

**Comment by NikoMuffin** [comment]
I've never had this issue. Running 1.9.0

**Comment by NikoMuffin** [comment]
> > I've never had this issue. Running 1.9.0
> 
> Why even post that? It was completely unnecessary. It still happens to me all the time and I thought maybe someone had a solution or update.

It was completely necessary IMO.  I run this app on 3 independent computers and I've never once experienced this.  Try wiping the install, starting over, pull newest legit version of prod.keys as it seems as though it's a local issue.

**Comment by harvestry-of-ghosts** [comment]
> > > I've never had this issue. Running 1.9.0
> > 
> > 
> > Why even post that? It was completely unnecessary. It still happens to me all the time and I thought maybe someone had a solution or update.
> 
> It was completely necessary IMO. I run this app on 3 independent computers and I've never once experienced this. Try wiping the install, starting over, pull newest legit version of prod.keys as it seems as though it's a local issue.

Yeah, well your opinion is simply wrong. It's been over a year since this was opened. Don't you think we've already tried a fresh install, installing it in a different location, checking our prod.keys file, and practically everything else under the sun that we could think of by now? There's nothing wrong with our installs or our prod.keys files. Period. Also, so you have three different PC's this is not happening to you on. Big deal. Guess what? There are three of us in here, all with different PC's, that it IS happening to.

You obviously missed two big things. 1) The app documentation that says prod.keys is OPTIONAL to begin with (although we do have the file), and 2) The part in this bug report saying that it doesn't happen 100% of the time.

This is what is occurring for those of us experiencing this bug. Sometimes the app opens and reads our games folder location and prod.keys file just fine on the very first try. Other times the app says it cannot find either and we need to close and re-open the app several times before it uses what is set in the settings.json file. Why? When no settings have been changed in-between opening and closing the app. Video demonstrating the bug:

https://youtu.be/ELe7F36bTOI

Why does the app give the errors the first four times trying to open it, but it was able to find both the games folder and prod.keys file perfectly fine on the fifth try? They were both obviously there the entire time or it wouldn't have found them on the 5th try. Sometimes it opens fine on the very first try, sometimes it's the second, sometimes the third, etc. etc. Explain, genius. Must be our non-legit prod.keys files like you said, right? LOL! Smfh. The rest of us will wait for your genius answer but thus far your comments have been worthless and completely unhelpful.
